name: "Pipeline for Development Environment"
description: "This workflow runs on pushes to the development branch and deploys the Terraform configuration for the dev environment."

on:
  push:
    branches:
      - development

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-region: "us-east-1"
    secrets:
      TF_AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      TF_AWS_STATEFILE_S3_BUCKET: ${{ secrets.AWS_STATEFILE_S3_BUCKET }}
      TF_AWS_LOCK_DYNAMODB_TABLE: ${{ secrets.AWS_LOCK_DYNAMODB_TABLE }}